#<Spring======================================================================
spring:
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #<============================================================================

  #<Kakao & login===============================================================
oauth:
  kakao:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}
    token-base-url: https://kauth.kakao.com/oauth/token
    user-info-request-url: https://kapi.kakao.com/v2/user/me
    scope:
      - account_email

cors:
  allowed-origin: ${CORS_ORIGIN}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: 50000000
  refresh-token-validity-ms: 604800000

login:
  success-url: ${LOGIN_SUCCESS_URL}
#<============================================================================

#<notification================================================================
firebase:
  config-path: ${FIREBASE_CONFIG_PATH:}
  base-url: ${BASE_URL}
#<============================================================================

#<s3==========================================================================
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
#<============================================================================

#<payment Gateway================================================================
payment:
  client-key: ${TOSS_CLIENT_KEY}
  secret-key: ${TOSS_SECRET_KEY}
  confirmUrl: ${TOSS_CONFIRM_URL}

#<============================================================================

#<slack=======================================================================
slack:
  token: ${SLACK_TOKEN}
#<============================================================================

#prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    enable:
      tomcat: true
      jvm: true
      http: true
---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-dev.properties

---
spring:
  config:
    activate:
      on-profile: prod
    import: classpath:application-prod.properties
